# Generated by Django 4.2.15 on 2024-11-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
