# Generated by Django 4.2.15 on 2024-11-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_recharge_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
