# Generated by Django 4.2.15 on 2024-09-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_user_first_name_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
