# Generated by Django 4.2.15 on 2024-10-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_customer',
        ),
    ]
