# Generated by Django 4.2.15 on 2024-10-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.CharField(blank=True, editable=False, max_length=19, null=True),
        ),
    ]
