# Generated by Django 4.2.15 on 2024-09-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
