# Generated by Django 4.2.15 on 2024-10-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
