# Generated by Django 4.2.15 on 2024-10-18 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0009_card_first_name_card_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardToCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialCard', models.CharField(max_length=16)),
                ('desCard', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cvv2', models.CharField(max_length=4)),
                ('expiration_month', models.CharField(max_length=2)),
                ('expiration_year', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
