# Generated by Django 4.2.15 on 2024-10-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_cardtocard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardtocard',
            old_name='expiration_month',
            new_name='cardMonth',
        ),
        migrations.RenameField(
            model_name='cardtocard',
            old_name='expiration_year',
            new_name='cardYear',
        ),
    ]
