# Generated by Django 4.2.15 on 2024-10-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_rename_expiration_month_cardtocard_cardmonth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardtocard',
            old_name='cardMonth',
            new_name='cardMonthy',
        ),
    ]
