# Generated by Django 4.2.15 on 2024-10-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_rename_cardmonth_cardtocard_cardmonthy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardtocard',
            old_name='cardMonthy',
            new_name='cardMonth',
        ),
    ]
