# Generated by Django 4.2.15 on 2024-10-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_rename_cardmonthy_cardtocard_cardmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtocard',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
