# Generated by Django 4.2.15 on 2024-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_alter_cardtocard_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtocard',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
