# Generated by Django 4.2.15 on 2024-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_alter_cardtocard_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtocard',
            name='created_at',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
