# Generated by Django 4.2.15 on 2024-11-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_cardtocard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtocard',
            name='desCardOwner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
