# Generated by Django 4.2.15 on 2024-12-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_advertisement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
